# Generated by Django 5.1.15 on 2025-12-24 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Research topic or query', max_length=500)),
                ('session_id', models.CharField(help_text='Unique session identifier (e.g., session_20251223_120000)', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('revision', 'Under Revision')], default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('discovery', 'Discovery'), ('demo', 'Demo')], default='demo', max_length=20)),
                ('session_directory', models.CharField(blank=True, help_text='Path to session directory', max_length=500)),
                ('transcript_path', models.CharField(blank=True, help_text='Path to session transcript', max_length=500)),
                ('error_message', models.TextField(blank=True, help_text='Error message if session failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Session',
                'verbose_name_plural': 'Research Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='Final research paper PDF', upload_to='research_papers/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, help_text='Paper title extracted from PDF', max_length=500)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='agents.researchsession')),
            ],
            options={
                'verbose_name': 'Research Paper',
                'verbose_name_plural': 'Research Papers',
            },
        ),
        migrations.CreateModel(
            name='PeerReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(help_text='Peer review feedback or revision requests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('revision_notes', models.TextField(blank=True, help_text='Notes from the revision process')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to='agents.researchsession')),
            ],
            options={
                'verbose_name': 'Peer Review Feedback',
                'verbose_name_plural': 'Peer Review Feedbacks',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Generated file', upload_to='research_files/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('csv', 'CSV Data'), ('json', 'JSON Data'), ('log', 'Log File'), ('txt', 'Text File'), ('png', 'Image'), ('other', 'Other')], help_text='Type of generated file', max_length=20)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of file contents')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='agents.researchsession')),
            ],
            options={
                'verbose_name': 'Generated File',
                'verbose_name_plural': 'Generated Files',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_anthropic_api_key', models.BinaryField(blank=True, help_text='Encrypted Anthropic API key', null=True)),
                ('default_research_mode', models.CharField(choices=[('discovery', 'Discovery Mode'), ('demo', 'Demo Mode')], default='demo', help_text='Default mode for new research sessions', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['owner', '-created_at'], name='agents_rese_owner_i_7e331e_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['session_id'], name='agents_rese_session_76b7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['status'], name='agents_rese_status_ed122a_idx'),
        ),
    ]
