# Generated by Django 5.1.15 on 2025-12-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='title',
            field=models.CharField(blank=True, help_text='Short display title (auto-generated from topic)', max_length=200),
        ),
    ]
